plugins:
  - jekyll-feed # RSS/Atom自動生成
  - jekyll-sitemap # サイトマップ自動生成
  - jekyll-last-modified-at # 最終更新日表示

# 目次作成
kramdown:
  parse_block_html: true


# サイト基本設定
name: "bujutuの宇宙"
url: "https://bujutu.github.io"
baseurl: ""


# マークダウン設定
markdown: kramdown
theme: minima


# Webアプリを除外（toku-com は Jekyll に触らせない）
exclude:
- toku-com


# 記事URL形式を分かりやすく
permalink: /posts/:year/:month/:day/:title/
