# サイトマップ自動生成
plugins:
  - jekyll-sitemap

# RSS/Atom自動生成
plugins:
  - jekyll-feed

# 目次作成
plugins:
  - jekyll-toc
toc:
  min_level: 2
  max_level: 4
  no_toc_section_class: "no-toc"


# サイト基本設定
name: "bujutuの宇宙"
url: "https://bujutu.github.io"
baseurl: ""


# マークダウン設定
markdown: kramdown
theme: minima


# Webアプリを除外（toku-com は Jekyll に触らせない）
exclude:
- toku-com


# 記事URL形式を分かりやすく
permalink: /posts/:year/:month/:day/:title/
